### ISSUE TITLE
Check if the world you died in is a Factions world

### ISSUE THREAD

**Issue by sini-kettu** [ToberoCat/ImprovedFaction#188]
**Is your feature request related to a problem? Please describe.**
Currently, if you die in a [Multiverse world](https://github.com/Multiverse/Multiverse-Core) that is not in the config file, your faction power still goes down. For instance, in my server, I have a set of SMP worlds and a set of Factions worlds, but when I die in any of the SMP worlds, my faction power goes down despite having a different world and inventory for Factions.

**Describe the solution you'd like**
A solution would be to check which world the player dies in, and if it's not a Factions world, do not decrease faction power.

Proposed fix in [PowerManager.java (line 61)](https://github.com/ToberoCat/ImprovedFaction/blob/master/Source/ImprovedFactions/ImprovedFactions/src/main/java/io/github/toberocat/improvedfactions/factions/power/PowerManager.java#L61):
```java
// ...
if (off.isOnline() && ImprovedFactionsMain.getPlugin().getConfig().getStringList("general.worlds").contains(off.getPlayer().getWorld().getName())) {
  // ...
}
```

**Comment by ToberoCat** [comment]
Alright thanks for the fix
