### ISSUE TITLE
[Bug] Color codes dont work in console

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFaction#201]
**Describe the bug**

![image](https://user-images.githubusercontent.com/26977075/182412191-0e6a56a5-4f94-494d-a3a3-216fe6dcc376.png)

**Error log from console**

**To Reproduce**

**Expected behavior**

These should proberly be removed or change to papers usage since the currently way is not supported by many things

**Screenshots**

**Version (please complete the following information):**
 - Plugin: 1.5
 - Server: 1.18.2 paper 387

**Additional context**

**Comment by ToberoCat** [comment]
Yes, they can't work for:
- Consoles not supporting colors
- Only paper like server software

To disable it there is a config option

**Comment by Josh65-2201** [comment]
My console and paper does support it just not using the §. It supports RGB HEX i believe older version also support it.

**Comment by ToberoCat** [comment]
Okay, it must be a problem with your console, as it need to support ChatColor.REd as example

**Comment by Josh65-2201** [comment]
Works find for everything else and 1.18.1 version of paper.
![image](https://user-images.githubusercontent.com/26977075/182436054-6a151e29-4a8a-40b3-9493-861916eb6ede.png)

**Comment by ToberoCat** [comment]
Okay, so for some reason the color doesn't get translated to chat color then.

Will have a look at the system that does that
