### ISSUE TITLE
Add world whitelist system

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFaction#9]
**Is your feature request related to a problem? Please describe.**
I use multiverse core for world manangement and currently this plugin gets enabled on all worlds from what i see and I dont want it too

**Describe the solution you'd like**
Add an enable in worlds feature

**Comment by ToberoCat** [comment]
Yes you already can do it. Go to config.yml. on here you will find a option allowing you to enable worlds. It's called general.worlds

Just add a - world name to add a world or remove a line to remove this world from working for none oped players

**Comment by Josh65-2201** [comment]
So ive added them but still comes up with "Wilderness" in any world on join. Also would be nice if it could be disable (apart for the f admin commands) for ops too with the message to go to the faction world to run them.

**Comment by ToberoCat** [comment]
You need to remove them so they won't work.

Will upload a version today that removes wilderness from disabled worlds. Disabling ops will be a config option there too.
Thanks for the suggestion
